### ISSUE TITLE
关于微信扫码登陆验证码的问题

### ISSUE THREAD

**Issue by xzshow** [suraxiuxiu/MoviePilot-Plugins#1]
大佬好，我在用企业微信扫码登陆时，腾讯发来验证码，要输入验证码才能登陆，这个怎么办呀，谢谢

**Comment by dengletail** [comment]
我也是同样的问题，怎么输入验证码呢

**Comment by hylf126** [comment]
同样问题。

**Comment by hylf126** [comment]
我来详细描述一下我遇到的问题。当MP里的企业微信的缓存失效时，手机微信会显示二维码，MP也显示同样的二维码，然后用微信无论扫描哪一个，选择登录之后都会收到来自腾讯的验证码，然而这个时候是没有地方输入验证码的，就陷入了死循环。只能去企业微信的网页，扫描那里的二维码，才能一次性登录，也不再有“验证码”这个东西。

**Comment by suraxiuxiu** [comment]
这个过段时间会加入输入验证码的功能  不过我这边不用输验证码  可能到时候得找一个人借个账号才能开发这个功能= =

**Comment by xzshow** [comment]
大佬牛B



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: suraxiuxiu ***@***.***&gt;
发送时间: 2024年11月26日 22:45
收件人: suraxiuxiu/MoviePilot-Plugins ***@***.***&gt;
抄送: xzshow ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [suraxiuxiu/MoviePilot-Plugins] 关于微信扫码登陆验证码的问题 (Issue #1)





 
这个过段时间会加入输入验证码的功能  不过我这边不用输验证码  可能到时候得找一个人借个账号才能开发这个功能= =
