### ISSUE TITLE
关于登陆问题

### ISSUE THREAD

**Issue by xzshow** [suraxiuxiu/MoviePilot-Plugins#10]
大佬有个问题，看下可否修改一下，当缓存失效后，感觉 只能从网页上扫码才行，在MP后台网页扫码可以登陆，但如果通过MP通知发来 的二维码，然后保存到手机中扫码登陆时，企业微信显示禁止访问。这不能登陆再无所谓，如果人不在电脑旁边，MP发来二维码也登不了，会不停地发送通知到微信里面，大佬能不能修改一下，如果缓存失效时，通知能不能修成 多久发送一次或者一天内发送三次这样，谢谢

**Comment by suraxiuxiu** [comment]
首先MP通知发来的二维码可以长按直接扫码登录，不用保存本地再选图片去扫码。
其次企业微信禁止这种图片识别扫码登录的话，可以参考下插件设置界面第二条账号风控提示。有群友实践过可以解决这个问题。
然后发通知间隔这个在计划中，后面会添加。
