### ISSUE TITLE
非常感谢大佬做的优秀插件,关于多出口ip的建议

### ISSUE THREAD

**Issue by MOMOTSI** [suraxiuxiu/MoviePilot-Plugins#11]
非常感谢大佬做的优秀插件，解决了无服务器中转的问题。

功能建议：多出口IP，插件是否可以增加两个检测IP服务地址输入框，这样可以对ip检测服务地址在路由分流，进行多IP返回，或者加一个遍历的开关，开启后获取所有服务地址返回，检测核对一致则上传一个，不一致上传多个。非常感谢大佬的插件。

路由上进行域名分流设置如下
wan1
https://myip.ipip.net/
https://ddns.oray.com/checkip
wan2
https://ip.3322.net/
https://4.ipw.cn/

**Comment by suraxiuxiu** [comment]
多出口IP在仓库主页有说明，我的建议是既然可以分流，那ip检测网址和企业微信地址都指定走同一个wan。这样可以避免多IP问题，毕竟发个通知也用不上多宽带。

**Comment by MOMOTSI** [comment]
> 多出口IP在仓库主页有说明，我的建议是既然可以分流，那ip检测网址和企业微信地址都指定走同一个wan。这样可以避免多IP问题，毕竟发个通知也用不上多宽带。
谢谢大佬回复，为了换ip有通知用的ddnsgo,snmpwalk命令解析的泛域名地址，因为命令缘故两个wan的ip次序不固定，如果不能支持多ip只能是用爱快再解析一个二级域名了,谢谢大佬做的插件

**Comment by suraxiuxiu** [comment]
不是很懂你的情况，你是指你的wan1 wan2绑定的宽带不固定吗  还是啥意思
既然你上面提到可以路由分流，  那把ip地址和企业微信地址全填wan1
这样检测到的IP都是wan1的，MP请求企业微信时也走wan1  这样可以吗
我对网络不是很懂哈 说错莫怪
