### ISSUE TITLE
缓存实现没有发送二维码

### ISSUE THREAD

**Issue by jianlongzhang1990** [suraxiuxiu/MoviePilot-Plugins#13]
缓存失效后微信没有收到登陆二维码？

**Comment by suraxiuxiu** [comment]
日志贴一下

**Comment by jianlongzhang1990** [comment]
![8cb423582bd586543cb21c68b2b5bdc](https://github.com/user-attachments/assets/cda6111f-9d97-4653-b613-6ab06f29e76c)
![8cb423582bd586543cb21c68b2b5bdc](https://github.com/user-attachments/assets/66c989f3-2430-4150-be81-8f27fe32f639)

**Comment by jianlongzhang1990** [comment]
![8cb423582bd586543cb21c68b2b5bdc](https://github.com/user-attachments/assets/d95e081d-98df-42ae-be34-b01c2625cb06)

**Comment by suraxiuxiu** [comment]
好的  不过你的日志看着的确经常超时  可以留意一下
