### ISSUE TITLE
建议支持更多通知方式（如 synologyChat/serverChan等），以应对 ip 和 cookie 同时过期的情况 

### ISSUE THREAD

**Issue by lengyu-lys** [suraxiuxiu/MoviePilot-Plugins#14]
如题，是否可以通过支持多种渠道通知的方式，实现ip 和 cookie 同时过期时可以有其它方式登录，这样就不需要手动通过页面进行登录了

**Comment by suraxiuxiu** [comment]
插件界面的登录二维码就是应对这种情况呀  直接扫码或者把二维码保存下来微信内扫图片也能登录的

**Comment by lengyu-lys** [comment]
> 插件界面的登录二维码就是应对这种情况呀 直接扫码或者把二维码保存下来微信内扫图片也能登录的

用第三方消息的话会比浏览器登录-找插件-点开要方便很多。不过您说的也有道理，除了方便一些以外并没有太大的区别

**Comment by suraxiuxiu** [comment]
这个暂时不考虑了，因为这种情况本来也很特殊，不常见，如果经常要使用的场景会考虑适配一下。
