### ISSUE TITLE
发送##登录企业微信  收不到二维码

### ISSUE THREAD

**Issue by bonnyandsky** [suraxiuxiu/MoviePilot-Plugins#15]
我微信推送配置已经完成，其他插件的推送我手机企业微信是能正常收到的。插件的日志这边也看不出来什么。
我mp是docker部署的，所以插件我下载的也是pw版本。不知道还有哪里设置的不对。
![57a8024b-33e6-4b73-b780-40f54f655739](https://github.com/user-attachments/assets/4fd27b1e-7e4d-495a-bd17-464f2214995e)
![image](https://github.com/user-attachments/assets/cbe4bdcd-7773-4ff1-abab-9d9a3fe71bf2)

**Comment by suraxiuxiu** [comment]
检查下MP通知设置里, 微信的通知消息类型是否全部勾上

**Comment by bonnyandsky** [comment]
> 检查下MP通知设置里, 微信的通知消息类型是否全部勾上

都勾上的，我其他插件的通知我手机微信都可以收到。不知道是因为cooking没过期所以没有答复二维码还是什么原因？
![image](https://github.com/user-attachments/assets/43ccec61-88b8-4d85-a3fb-74880ef919b4)

**Comment by suraxiuxiu** [comment]
如果发送登录命令时cookie没有过期，MP会回复一条"缓存有效，无需登录"的消息
会不会是MP没有收到你的命令，你试一下发送别的随便什么命令或者文字，看看MP会回复你吗 
或者你试试在浏览器登录企业微信， 把MP的cookie给挤下线，插件设置cookie失效通知周期为* * * * *  看看插件的失效通知能发送到微信上不
问题比较奇怪，只能这样试着排查了

**Comment by bonnyandsky** [comment]
> 如果发送登录命令时cookie没有过期，MP会回复一条"缓存有效，无需登录"的消息 会不会是MP没有收到你的命令，你试一下发送别的随便什么命令或者文字，看看MP会回复你吗 或者你试试在浏览器登录企业微信， 把MP的cookie给挤下线，插件设置cookie失效通知周期为* * * * * 看看插件的失效通知能发送到微信上不 问题比较奇怪，只能这样试着排查了

mp可以收到我发的消息的。

**Comment by suraxiuxiu** [comment]
插件设置里的指定微信成员id有填东西吗 默认留空那项

**Comment by bonnyandsky** [comment]
> 插件设置里的指定微信成员id有填东西吗 默认留空那项

好了。问题解决了。主要就是我字打错了。后面的问题是因为延时导致的。现在把通知时间从* * * * *改成长一点的半小时一次，手机可以登录企业微信了。问题解决。谢谢帮助

**Comment by suraxiuxiu** [comment]
上面提示无效,  后面登录提示有效可能是同步cookiecloud的有效cookie来使用了
开了CC的话会优先同步CC的
顺便问一下为啥MP发你的回复内容会带上"点击查看xxxx"这些字样?
