### ISSUE TITLE
企业微信无法扫描二维码登录

### ISSUE THREAD

**Issue by yf-9186** [suraxiuxiu/MoviePilot-Plugins#16]
发送#登录企业微信，返回二维码后，企业微信识别二维码无法登录，提示 已停止本次访问，如需访问企业微信管理后台，请通过官网扫码登录

**Comment by suraxiuxiu** [comment]
账号问题 详情看插件主页说明
https://github.com/suraxiuxiu/MoviePilot-Plugins?tab=readme-ov-file#%E6%97%A0%E6%B3%95%E9%80%9A%E8%BF%87%E8%AF%86%E5%88%AB%E5%9B%BE%E7%89%87%E4%BA%8C%E7%BB%B4%E7%A0%81%E7%99%BB%E5%BD%95
