### ISSUE TITLE
能加一个 双公网ip 的检测么

### ISSUE THREAD

**Issue by wanpijun2** [suraxiuxiu/MoviePilot-Plugins#7]
我是双宽带   发现贵插件在检测到一个的时候 就去 企业微信添加更改了 能优化下嘛  行不通的话 也没事

**Comment by suraxiuxiu** [comment]
双IP检测不好做（我菜），插件端无论请求多少次IP检测网站，都无法保证会返回两个宽带的IP，因为这是路由端负责的，可能请求一百次也是分配A宽带去访问，所以在路由端设置可以很容易解决这个问题。参考相同提问
https://github.com/suraxiuxiu/MoviePilot-Plugins/issues/3
